### PR TITLE
32bit system test fix and add pytest to appvayor

### PR DESCRIPTION
**Pull request by zeruniverse**
#33 goes here. After force rebase, that one is closed automatically

### CODE REVIEW

**Comment by zeruniverse** [comment]
@william-silversmith this is ready to review & merge. After this is merged, could you help make a release and upload to Pypi?

**Comment by william-silversmith** [comment]
This is okay, but ideally we would set a special condition on the encoding bits so that if a `MemoryError` occurs it's okay.

**Comment by william-silversmith** [comment]
Okay, the wheels are uploaded to PyPI! Let me know if you need more help. Thanks so much for the contribution!

**Comment by zeruniverse** [comment]
Thanks!

**Pull request merged**
