### PR TITLE
32bit system fix and add pytest to appvayor

### PR DESCRIPTION
**Pull request by zeruniverse**
Needs merge of https://github.com/seung-lab/DracoPy/pull/32 first and then do rebase

### CODE REVIEW

**Comment by zeruniverse** [comment]
Failed upon adding just pytest to appveyor x86 platform. Likely caused by 4Gi RAM upper limit on x86

https://ci.appveyor.com/project/william-silversmith/dracopy/builds/44407279

**Comment by william-silversmith** [comment]
Hi Jeffery, 

Let me know when this PR is ready for review. There's been a lot of activity on it so I've been unsure when it is ready.

Will

**Comment by zeruniverse** [comment]
Hi @william-silversmith ,

It’s already done and most of changes here are actually from this https://github.com/seung-lab/DracoPy/pull/32

after the above PR merged, I’ll do a rebase and the change will look cleaner

**Comment by zeruniverse** [comment]
#32 is ready for review

**Comment by william-silversmith** [comment]
Hi! would you mind performing the rebase? Thanks!

**Pull request merged**
