### PR TITLE
Update Python / Cython / Draco versions

### PR DESCRIPTION
**Pull request by zeruniverse**
Thanks for this great Python binding!

I'm submitting this PR to mainly update draco version to current HEAD of draco master branch so I can work on top of it for other features. I'm also adding Python3.10 to Dockerfile

### CODE REVIEW

**Comment by william-silversmith** [comment]
Hi there! Thanks for this PR! I'm very happy you're updating the core draco library.

The more important thing I'd not here is that I'm having trouble installing it though I'm sure with some struggles I could do it. Even though shared libraries are more convenient for some users, I prefer to package DracoPy with a static compilation. Otherwise many people will struggle to install this package and be confused by differing behavior. This package is very crucial for my lab and many of the people using it are not the best programmers and may not understand the subtleties here. 

Would you mind switching it back to static linking? Otherwise, so far so good!

**Comment by zeruniverse** [comment]
thanks for your reply! Updating the core library is pretty important as current implementation consumes huge amount of memory when quantization bits are above 28 (not sure if that is a bug).

for your question:
1. i believe the drao is already static, if you check my latest code, i changed cmake flag from sharedLib to PIC, and i didn't see .so files being built locally during compilation
2. i have successfully built the wheel (3.7) in docker using the dockerfile (which i also updated), and i saw CI for PR also built successfully on Windows. which system are you using and what trouble did you get when installing it?

**Comment by william-silversmith** [comment]
Interesting, thanks for the report! We only use 10 or 16 bits, so we never encountered that issue. It's good to know this will fix it! 

I tested the latest code, and I was able to compile it much more easily. Previously, I think it was expecting that I installed a dynamic shared library correctly on MacOS 12.3. Let me know when this is ready for review, I think we can expect to get it merged pretty quickly.

**Comment by zeruniverse** [comment]
I believe it’s ready for review. Let me know if it fails somewhere.

By the way, i only have Ubuntu System. So i cannot locally test it on
Windows or Mac. It would be helpful if you can help verify things works on
those system (like building wheels on machine A and install it on machine B)

After this getting merged, i’ll implement the sequential encoding which
preserves face and vertices order

**Review by william-silversmith — APPROVED** [review]
Some of the suggestions here are fixed in the next PR.

**Pull request merged**
